clone_depth: 5
environment:
  nodejs_version: "12.18"
platform: x64 # flow needs 64b platforms
# Install scripts. (runs after repo cloning)
install:
  # 1. Select the right node
  - ps: Install-Product node $env:nodejs_version $env:platform
  # 2. Setup the project
  - yarn install --frozen-lockfile

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - yarn versions
  # run tests
  - yarn license-check
  - yarn test-alex
  - yarn lint
  - yarn flow:ci
  - yarn test
  - yarn build-prod:quiet

cache:
  - node_modules

# Don't actually build.
build: off
